cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  7 # use node version 7
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
- npm install # install node module
- npm run build # build project
install:
  npm install -g firebase-tools # install firebase-cli
after_success:
- firebase use --token ${1/k6tJ91HZ5MTZlvn5mZdAMrFX3h97CDZcIrVzb-dltjU} # set firebase token
- firebase use --add ${sparking-d3380} # set current project
- firebase deploy --non-interactive --token "${1/k6tJ91HZ5MTZlvn5mZdAMrFX3h97CDZcIrVzb-dltjU}" # deploy project